name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  test-runner:
    runs-on: self-hosted
    
    steps:
    - name: Check runner info
      run: |
        echo "Runner name: $RUNNER_NAME"
        echo "Runner OS: $RUNNER_OS"
        echo "Runner arch: $RUNNER_ARCH"
        whoami
        pwd
        
    - name: Check Docker availability
      run: |
        docker --version
        docker ps
        
    - name: Test basic commands
      run: |
        echo "Testing basic commands..."
        date
        uptime
        df -h
        
    - name: Checkout code (optional)
      uses: actions/checkout@v4
      
    - name: List project files
      run: ls -la